services:
  app:
    container_name: website-staging
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    build:
      context: ../../
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      dockerfile: docker/website-staging/Dockerfile.staging
    restart: always
    ports:
      - ${EXPOSABLE_PORT}:3000
