services:
  app:
    container_name: website-dev
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    build:
      context: ../../
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      dockerfile: docker/dev/Dockerfile.dev
    restart: always
    volumes:
      - ../../src:/app/src
      - ../../public:/app/public
    ports:
      - ${EXPOSABLE_PORT}:3000
